// ─── US Vehicle Makes & Models (2000–present) ────────────────────────────────
export const MAKE_MODELS = {
  "Acura": ["ILX","Integra","MDX","NSX","RDX","RLX","RSX","TL","TLX","TSX","ZDX"],
  "Alfa Romeo": ["4C","Giulia","Giulietta","Stelvio","Tonale"],
  "Aston Martin": ["DB11","DB9","DBS","Rapide","Vantage","Virage"],
  "Audi": ["A3","A4","A5","A6","A7","A8","e-tron","Q3","Q4 e-tron","Q5","Q7","Q8","R8","RS3","RS5","RS6","RS7","S3","S4","S5","S6","S7","S8","SQ5","SQ7","TT"],
  "Bentley": ["Bentayga","Continental GT","Flying Spur","Mulsanne"],
  "BMW": ["1 Series","2 Series","3 Series","4 Series","5 Series","6 Series","7 Series","8 Series","i3","i4","i7","iX","M2","M3","M4","M5","M8","X1","X2","X3","X4","X5","X6","X7","XM","Z4"],
  "Buick": ["Cascada","Enclave","Encore","Encore GX","Envision","LaCrosse","LeSabre","Lucerne","Park Avenue","Rainier","Regal","Rendezvous","Terraza","Verano"],
  "Cadillac": ["ATS","CT4","CT5","CT6","CTS","DeVille","DTS","Escalade","Escalade ESV","EXT","Lyriq","SRX","STS","XT4","XT5","XT6","XTS"],
  "Chevrolet": ["Astro","Avalanche","Aveo","Blazer","Camaro","Captiva","City Express","Cobalt","Colorado","Corvette","Cruze","Equinox","Express","HHR","Impala","Malibu","Monte Carlo","Orlando","Silverado 1500","Silverado 2500HD","Silverado 3500HD","Sonic","Spark","Suburban","Tahoe","Tracker","TrailBlazer","Traverse","Trax","Uplander","Volt"],
  "Chrysler": ["200","300","300M","Aspen","Crossfire","Grand Voyager","Pacifica","PT Cruiser","Sebring","Town & Country","Voyager"],
  "Dodge": ["Avenger","Caliber","Challenger","Charger","Dart","Durango","Grand Caravan","Journey","Magnum","Neon","Nitro","Ram 1500","Viper"],
  "Ferrari": ["488","812 Superfast","California","F8","GTC4Lusso","Portofino","Roma","SF90"],
  "FIAT": ["124 Spider","500","500L","500X"],
  "Ford": ["Bronco","Bronco Sport","C-Max","Edge","Escape","Expedition","Explorer","F-150","F-250 Super Duty","F-350 Super Duty","Fiesta","Five Hundred","Flex","Focus","Freestyle","Fusion","Galaxy","GT","Maverick","Mustang","Mustang Mach-E","Ranger","Taurus","Thunderbird","Transit","Transit Connect"],
  "Genesis": ["G70","G80","G90","GV70","GV80"],
  "GMC": ["Acadia","Canyon","Envoy","Jimmy","Safari","Savana","Sierra 1500","Sierra 2500HD","Sierra 3500HD","Sonoma","Terrain","Yukon","Yukon XL"],
  "Honda": ["Accord","Civic","CR-V","CR-Z","Crosstour","Element","Fit","HR-V","Insight","Odyssey","Passport","Pilot","Prologue","Ridgeline","S2000"],
  "Hummer": ["H1","H2","H3"],
  "Hyundai": ["Accent","Azera","Elantra","Entourage","Equus","Genesis","Genesis Coupe","Ioniq","Ioniq 5","Ioniq 6","Kona","Kona Electric","Nexo","Palisade","Santa Cruz","Santa Fe","Sonata","Tiburon","Tucson","Veloster","Venue","Veracruz"],
  "INFINITI": ["EX35","FX35","FX37","FX50","G35","G37","I35","JX35","M35","M37","M56","Q30","Q45","Q50","Q60","Q70","QX30","QX50","QX55","QX56","QX60","QX70","QX80"],
  "Jaguar": ["E-Pace","F-Pace","F-Type","I-Pace","S-Type","X-Type","XE","XF","XJ","XK"],
  "Jeep": ["Cherokee","Commander","Compass","Gladiator","Grand Cherokee","Grand Cherokee L","Grand Wagoneer","Liberty","Patriot","Renegade","Wagoneer","Wrangler"],
  "Kia": ["Amanti","Borrego","Cadenza","Carnival","EV6","Forte","K5","K900","Niro","Optima","Rio","Sedona","Seltos","Sorento","Soul","Sportage","Stinger","Stonic","Telluride"],
  "Lamborghini": ["Aventador","Huracan","Urus"],
  "Land Rover": ["Defender","Discovery","Discovery Sport","Freelander","LR2","LR3","LR4","Range Rover","Range Rover Evoque","Range Rover Sport","Range Rover Velar"],
  "Lexus": ["CT","ES","GS","GX","HS","IS","LC","LS","LX","NX","RC","RX","RZ","SC","UX"],
  "Lincoln": ["Aviator","Blackwood","Continental","Corsair","LS","Mark LT","MKC","MKS","MKT","MKX","MKZ","Nautilus","Navigator","Town Car","Zephyr"],
  "Maserati": ["Ghibli","GranTurismo","Grecale","Levante","MC20","Quattroporte"],
  "Mazda": ["2","3","5","6","CX-3","CX-30","CX-5","CX-50","CX-7","CX-9","CX-90","Miata MX-5","MPV","RX-8","Tribute"],
  "McLaren": ["540C","570S","600LT","720S","Artura","GT"],
  "Mercedes-Benz": ["A-Class","AMG GT","C-Class","CLA","CLK","CLS","E-Class","EQB","EQC","EQE","EQS","G-Class","GL-Class","GLA","GLB","GLC","GLE","GLS","M-Class","Metris","R-Class","S-Class","SL","SLC","SLK","Sprinter"],
  "MINI": ["Clubman","Convertible","Countryman","Coupe","Hardtop","Paceman","Roadster"],
  "Mitsubishi": ["3000GT","Diamante","Eclipse","Eclipse Cross","Endeavor","Galant","Lancer","Mirage","Montero","Montero Sport","Outlander","Outlander PHEV","Outlander Sport","Raider"],
  "Nissan": ["370Z","400Z","Altima","Armada","Frontier","GT-R","Juke","Kicks","Leaf","Maxima","Murano","NV","NV200","NX","Pathfinder","Quest","Rogue","Rogue Sport","Sentra","Titan","Titan XD","Versa","Xterra"],
  "Oldsmobile": ["Alero","Aurora","Bravada","Intrigue","Silhouette"],
  "Pontiac": ["Aztek","Bonneville","G5","G6","G8","Grand Am","Grand Prix","Montana","Solstice","Torrent","Vibe"],
  "Porsche": ["718 Boxster","718 Cayman","911","Cayenne","Macan","Panamera","Taycan"],
  "RAM": ["1500","2500","3500","4500","5500","C/V","Dakota","ProMaster","ProMaster City"],
  "Rolls-Royce": ["Cullinan","Dawn","Ghost","Phantom","Silver Seraph","Wraith"],
  "Saab": ["9-3","9-5","9-7X"],
  "Saturn": ["Aura","Ion","Outlook","Relay","Sky","Vue"],
  "Scion": ["FR-S","iA","iM","iQ","tC","xA","xB","xD"],
  "Subaru": ["Ascent","BRZ","Crosstrek","Forester","Impreza","Legacy","Outback","Solterra","Tribeca","WRX"],
  "Tesla": ["Cybertruck","Model 3","Model S","Model X","Model Y","Roadster"],
  "Toyota": ["4Runner","86","Avalon","bZ4X","Camry","Celica","Corolla","Echo","FJ Cruiser","GR86","GR Corolla","GR Supra","Highlander","Land Cruiser","Matrix","MR2","Prius","Prius C","Prius Prime","Prius V","RAV4","RAV4 Prime","Sequoia","Sienna","Solara","Tacoma","Tundra","Venza","Yaris"],
  "Volkswagen": ["Arteon","Atlas","Beetle","CC","EOS","Golf","Golf R","GTI","ID.4","Jetta","Passat","Phaeton","Routan","Taos","Tiguan","Touareg"],
  "Volvo": ["C30","C40","C70","S40","S60","S80","S90","V40","V60","V70","V90","XC40","XC60","XC70","XC90"],
};

export const MAKES = Object.keys(MAKE_MODELS).sort();
